### ISSUE TITLE
Any reason for not putting the script in /config/scripts?

### ISSUE THREAD

**Issue by NoLooseEnds** [confirm/edgerouter-dnsmasq-updater#1]
Thanks for this. Perfect for me when going from OPNsense to an EdgeRouter 4.

Is there any reason for not putting the script in `/config/scripts`? As far as I can understand it shouldn't break anything when updating? At worst you get an extra file in `/etc/`

```
[ system task-scheduler task update-static-hosts executable path /usr/local/bin/update-static-hosts.py ]
Warning: '/usr/local/bin/update-static-hosts.py' lies outside of /config/scripts directory. It will not get preserved during image upgrade.
```

**Comment by domibarton** [comment]
Whoot? I didn't knew about that, so why not! :D

**Comment by NoLooseEnds** [comment]
Great! :)
